language: node_js
sudo: false

node_js:
  - 6
  - 8
  - 10
  - 12

install:
  - npm install
  - npm install -g codecov

script:
  - node --version
  - npm --version
  - npm test

after_script:
  - codecov
